import time
import csv
import math
import os

# -----------------------------
# CONFIGURATION
# -----------------------------
XPLANE_FILENAME = "B_Flight_5.txt"          # The file generated by X Plane
PLAYBACK_SPEED = 0                          # Seconds to wait between lines (0 = instant processing)

# Modern stall warning system parameters (FAR 25.207 compliant)
# Reference aircraft parameters (adjust for your specific aircraft)
AIRCRAFT_WEIGHT_LBS = 3400.0                # Reference aircraft weight in pounds
VS_1G_REF_KT = 75.0                         # 1G stall speed at reference weight (clean config)
WING_AREA_SQ_FT = 174.0                     # Wing reference area
RHO_SEA_LEVEL = 0.002377                    # Air density at sea level (slugs/ft³)

# Certification margins (FAR 25.207)
STALL_WARNING_MARGIN_KT = 5.0               # Minimum warning margin above stall (FAR requirement)
MARGIN_MULTIPLIER = 1.07                    # Additional 7% margin (conservative)
AOA_STALL_DEG = 16.0                        # Critical angle of attack (aircraft specific)
AOA_WARNING_MARGIN_DEG = 2.5                # AoA margin before stall (typical: 2-3 degrees)

# Ice protection adjustment
ICE_CONDITION_SPEED_PENALTY_KT = 10.0       # Speed increase when icing detected
ICE_CONDITION_AOA_ADVANCE_DEG = 1.5         # AoA warning advancement in icing

# Sensor redundancy and voting
SENSOR_DISAGREEMENT_THRESHOLD_DEG = 3.0     # Max allowed difference between AoA sensors
SENSOR_FAIL_AOA_VALUE = 999.9               # Indicator of failed sensor

# Hysteresis and latching
SPEED_HYSTERESIS_KT = 2.0                   # Hysteresis band for speed-based warning
AOA_HYSTERESIS_DEG = 1.0                    # Hysteresis band for AoA-based warning
WARNING_LATCH_TIME_SEC = 1.0                # Minimum warning duration (prevents flicker)

# Output
OUTPUT_FILENAME = f"modern_stall_results_{int(time.time())}.csv"

# Column preferences in your data file
SPEED_CANDIDATES = ["_Vind,_kias", "Vtrue,_ktas", "Vtrue,_ktgs"]
AOA_CANDIDATES = ["alpha,__deg"]
ALT_CANDIDATES = ["p-alt,ftMSL", "___CG,ftMSL", "terrn,ftMSL"]
TIME_CANDIDATES = ["_real,_time", "_totl,_time", "frame,_time"]

# -----------------------------
# HELPER FUNCTIONS
# -----------------------------
def clip(x, lo, hi):
    """Clamp value between lo and hi"""
    return max(lo, min(x, hi))

def parse_header_line(header_line: str):
    """Parse header line from X-Plane data file"""
    parts = [p.strip() for p in header_line.strip().split("|")]
    parts = [p for p in parts if len(p) > 0]
    return parts

def parse_data_line(data_line: str):
    """Parse data line and convert to floats"""
    raw = [p.strip() for p in data_line.strip().split("|")]
    raw = [p for p in raw if len(p) > 0]
    values = []
    for item in raw:
        try:
            values.append(float(item))
        except ValueError:
            return None
    return values

def pick_column_index(columns, candidates):
    """Find first matching column from candidates list"""
    for name in candidates:
        if name in columns:
            return columns.index(name), name
    return None, None

# -----------------------------
# MODERN STALL WARNING LOGIC
# -----------------------------

def calculate_dynamic_stall_speed(
    weight_lbs: float,
    load_factor: float,
    altitude_ft: float,
    icing_detected: bool = False,
    flaps_deployed: bool = False
) -> tuple[float, float]:
    """
    Calculate dynamic stall speed based on actual conditions.
    
    Modern systems adjust stall speed for:
    - Weight (Vs proportional to sqrt(W))
    - Load factor (Vs proportional to sqrt(n))
    - Altitude/air density
    - Configuration (flaps, gear)
    - Icing conditions
    
    Returns: (stall_speed_kts, warning_speed_kts)
    
    Formula: Vs = Vs_ref * sqrt(W/W_ref) * sqrt(n)
    where n is load factor
    """
    # Weight correction: Vs proportional to sqrt(weight ratio)
    weight_ratio = weight_lbs / AIRCRAFT_WEIGHT_LBS
    weight_factor = math.sqrt(max(0.5, min(2.0, weight_ratio)))  # Limit range
    
    # Load factor correction: Vs proportional to sqrt(load factor)
    # In level flight n=1, in 60° bank n=2, etc.
    load_factor = max(1.0, load_factor)  # Minimum 1G
    load_factor_multiplier = math.sqrt(load_factor)
    
    # Altitude/density correction (simplified - assumes standard atmosphere)
    # Air density decreases with altitude, affecting stall speed
    # rho = rho_0 * exp(-altitude / 30000) approximately
    density_ratio = math.exp(-altitude_ft / 30000.0)
    density_factor = 1.0 / math.sqrt(max(0.3, density_ratio))
    
    # Configuration adjustments
    config_factor = 1.0
    if flaps_deployed:
        config_factor = 0.85  # Flaps reduce stall speed ~15%
    
    # Base stall speed with all corrections
    vs_actual = VS_1G_REF_KT * weight_factor * load_factor_multiplier * density_factor * config_factor
    
    # Ice protection margin (FAR 25.207h requires additional margin in icing)
    ice_penalty = ICE_CONDITION_SPEED_PENALTY_KT if icing_detected else 0.0
    vs_actual += ice_penalty
    
    # Warning speed: FAR 25.207 requires warning at least 5 knots above stall
    # We add conservative margin
    warning_speed = vs_actual + STALL_WARNING_MARGIN_KT
    warning_speed *= MARGIN_MULTIPLIER  # Additional safety margin
    
    return vs_actual, warning_speed


def calculate_aoa_warning_threshold(icing_detected: bool = False) -> tuple[float, float]:
    """
    Calculate angle of attack warning threshold.
    
    Modern systems use AoA as primary stall indicator.
    Warning threshold is set below critical AoA with margin.
    
    Returns: (warning_aoa_deg, clear_aoa_deg)
    """
    # Ice advancement: warn earlier in icing conditions
    ice_advance = ICE_CONDITION_AOA_ADVANCE_DEG if icing_detected else 0.0
    
    warning_aoa = AOA_STALL_DEG - AOA_WARNING_MARGIN_DEG - ice_advance
    clear_aoa = warning_aoa - AOA_HYSTERESIS_DEG
    
    return warning_aoa, clear_aoa


def dual_sensor_voting(aoa_sensor_1: float, aoa_sensor_2: float) -> tuple[float, bool, str]:
    """
    Implement dual sensor voting logic for redundancy.
    
    Modern aircraft use 2+ independent AoA sensors with cross-checking.
    If sensors disagree significantly, flag as sensor fault.
    
    Returns: (voted_aoa, sensors_valid, status_message)
    """
    # Check for sensor failures
    sensor1_failed = abs(aoa_sensor_1 - SENSOR_FAIL_AOA_VALUE) < 0.1
    sensor2_failed = abs(aoa_sensor_2 - SENSOR_FAIL_AOA_VALUE) < 0.1
    
    if sensor1_failed and sensor2_failed:
        return 0.0, False, "BOTH_SENSORS_FAILED"
    elif sensor1_failed:
        return aoa_sensor_2, True, "SENSOR_1_FAILED_USING_2"
    elif sensor2_failed:
        return aoa_sensor_1, True, "SENSOR_2_FAILED_USING_1"
    
    # Both sensors operational - check for disagreement
    disagreement = abs(aoa_sensor_1 - aoa_sensor_2)
    
    if disagreement > SENSOR_DISAGREEMENT_THRESHOLD_DEG:
        # Sensors disagree - sensor fault condition
        # Conservative approach: use higher reading (more cautious)
        voted_aoa = max(aoa_sensor_1, aoa_sensor_2)
        return voted_aoa, False, f"SENSOR_DISAGREE_{disagreement:.1f}deg"
    else:
        # Sensors agree - take average
        voted_aoa = (aoa_sensor_1 + aoa_sensor_2) / 2.0
        return voted_aoa, True, "SENSORS_AGREE"


def modern_stall_warning_system(
    ias_kt: float,
    aoa_deg: float,
    weight_lbs: float,
    load_factor: float,
    altitude_ft: float,
    t_sec: float,
    icing_detected: bool,
    flaps_deployed: bool,
    prev_warning_state: bool,
    last_warning_time: float | None,
    aoa_sensor_2: float = None  # Second AoA sensor for redundancy
) -> tuple[bool, float, str, dict]:
    """
    Modern certification-compliant stall warning system.
    
    Implements:
    - Dual sensor voting (if available)
    - Dynamic stall speed calculation
    - FAR 25.207 compliant margins
    - Hysteresis to prevent nuisance warnings
    - Warning latch to ensure minimum duration
    - Ice protection awareness
    
    Returns: (warning_active, last_warning_time, reason, debug_info)
    """
    
    # Step 1: Sensor voting (if dual sensors available)
    if aoa_sensor_2 is not None:
        voted_aoa, sensors_valid, sensor_status = dual_sensor_voting(aoa_deg, aoa_sensor_2)
        if not sensors_valid:
            # Sensor fault - use degraded mode or default to conservative
            pass  # Continue with single sensor in this implementation
        aoa_deg = voted_aoa
    else:
        sensor_status = "SINGLE_SENSOR"
    
    # Step 2: Calculate dynamic thresholds based on current conditions
    vs_actual, vs_warning = calculate_dynamic_stall_speed(
        weight_lbs, load_factor, altitude_ft, icing_detected, flaps_deployed
    )
    
    aoa_warning_threshold, aoa_clear_threshold = calculate_aoa_warning_threshold(icing_detected)
    
    # Step 3: Evaluate warning conditions
    # FAR 25.207: Warning must activate based on EITHER speed OR AoA
    
    # Speed-based trigger (with hysteresis)
    speed_trigger = ias_kt < (vs_warning - SPEED_HYSTERESIS_KT)
    speed_clear = ias_kt > (vs_warning + SPEED_HYSTERESIS_KT)
    
    # AoA-based trigger (primary input for modern systems)
    aoa_trigger = aoa_deg > aoa_warning_threshold
    aoa_clear = aoa_deg < aoa_clear_threshold
    
    # Step 4: Warning state logic with latching
    warning_active = prev_warning_state
    reason = "NORMAL"
    
    # Check if latch is active (warning must stay on for minimum duration)
    def latch_is_active():
        if last_warning_time is None:
            return False
        return (t_sec - last_warning_time) < WARNING_LATCH_TIME_SEC
    
    # Trigger warning if EITHER condition met
    if speed_trigger or aoa_trigger:
        warning_active = True
        last_warning_time = t_sec
        
        # Determine primary trigger reason
        if speed_trigger and aoa_trigger:
            reason = "SPEED_AND_AOA_WARNING"
        elif speed_trigger:
            reason = "SPEED_LOW_WARNING"
        else:
            reason = "AOA_HIGH_WARNING"
    
    else:
        # No active triggers - can we clear?
        if warning_active:
            if latch_is_active():
                # Keep warning on due to latch
                reason = "WARNING_LATCHED"
            else:
                # Check if both conditions are clear
                if speed_clear and aoa_clear:
                    warning_active = False
                    reason = "WARNING_CLEARED"
                else:
                    # Still in warning region (hysteresis band)
                    reason = "WARNING_HYSTERESIS"
        else:
            reason = "NORMAL_FLIGHT"
    
    # Step 5: Create debug info dictionary
    debug_info = {
        "vs_actual_kt": vs_actual,
        "vs_warning_kt": vs_warning,
        "aoa_warning_deg": aoa_warning_threshold,
        "aoa_clear_deg": aoa_clear_threshold,
        "load_factor": load_factor,
        "sensor_status": sensor_status,
        "icing_detected": icing_detected,
        "margin_to_stall_kt": ias_kt - vs_actual,
        "margin_to_aoa_stall_deg": aoa_warning_threshold - aoa_deg
    }
    
    return warning_active, last_warning_time, reason, debug_info


def modern_risk_assessment(
    ias_kt: float,
    aoa_deg: float,
    vs_actual: float,
    aoa_warning_threshold: float,
    load_factor: float
) -> float:
    """
    Modern risk assessment based on energy state and proximity to stall.
    
    Unlike simple threshold logic, this provides graduated risk assessment
    similar to modern flight envelope protection systems.
    
    Risk factors:
    - Energy margin (speed above stall)
    - AoA margin (angle below critical)
    - Load factor stress
    
    Returns: Risk value in [0, 1] where:
        0.0-0.3 = Normal flight
        0.3-0.6 = Caution (approaching limits)
        0.6-0.85 = Warning (near stall)
        0.85-1.0 = Imminent stall
    """
    
    # Energy margin: How much speed above stall?
    # At 1.3*Vs (typical approach speed) risk should be low
    # At 1.0*Vs (stall) risk should be 1.0
    if vs_actual > 0:
        speed_ratio = ias_kt / vs_actual
        # Map: 1.5+ -> 0.0, 1.3 -> 0.2, 1.1 -> 0.5, 1.0 -> 0.9
        if speed_ratio >= 1.5:
            speed_risk = 0.0
        elif speed_ratio <= 1.0:
            speed_risk = 0.95
        else:
            # Exponential increase as approaching stall
            speed_risk = (1.5 - speed_ratio) / 0.5
            speed_risk = clip(speed_risk ** 1.5, 0.0, 0.95)
    else:
        speed_risk = 0.5
    
    # AoA margin: How close to critical angle?
    if aoa_warning_threshold > 0:
        aoa_margin = aoa_warning_threshold - aoa_deg
        # Positive margin = safe, negative = exceeded warning
        if aoa_margin >= 2.0:
            aoa_risk = 0.0
        elif aoa_margin <= -1.0:
            aoa_risk = 0.95
        else:
            # Linear ramp from safe to warning
            aoa_risk = (2.0 - aoa_margin) / 3.0
            aoa_risk = clip(aoa_risk, 0.0, 0.95)
    else:
        aoa_risk = 0.5
    
    # Load factor contribution: Higher G = higher stall speed
    # At 1G risk modifier = 0, at 2G+ add extra risk
    load_risk = 0.0
    if load_factor > 1.5:
        load_risk = (load_factor - 1.5) * 0.15
        load_risk = clip(load_risk, 0.0, 0.3)
    
    # Combine risks: Speed and AoA are primary, load is modifier
    # Weight: 60% speed, 30% AoA, 10% load factor
    combined_risk = (0.60 * speed_risk) + (0.30 * aoa_risk) + (0.10 * load_risk)
    
    # Apply nonlinearity to emphasize high-risk states
    combined_risk = combined_risk ** 1.1
    
    return clip(combined_risk, 0.0, 1.0)


# -----------------------------
# MAIN SIMULATION
# -----------------------------
if not os.path.exists(XPLANE_FILENAME):
    print(f"ERROR: Could not find '{XPLANE_FILENAME}'")
    print("Copy the Data.txt file into the same folder as this script.")
    raise SystemExit(1)

print("="*70)
print("MODERN STALL WARNING SYSTEM SIMULATOR")
print("FAR 25.207 Compliant with Dual Sensor Redundancy")
print("="*70)
print(f"Opening flight log: {XPLANE_FILENAME}")
print(f"Simulation step delay: {PLAYBACK_SPEED} seconds")
print(f"Writing output: {OUTPUT_FILENAME}")
print()
print("Aircraft Configuration:")
print(f"  Reference Weight: {AIRCRAFT_WEIGHT_LBS:.0f} lbs")
print(f"  1G Stall Speed: {VS_1G_REF_KT:.1f} kts")
print(f"  Warning Margin: {STALL_WARNING_MARGIN_KT:.1f} kts above stall")
print(f"  Critical AoA: {AOA_STALL_DEG:.1f}°")
print(f"  Warning AoA Margin: {AOA_WARNING_MARGIN_DEG:.1f}°")
print("="*70)
print()

with open(XPLANE_FILENAME, "r", errors="ignore") as f:
    lines = f.readlines()

# Find header line
header_index = None
for i, line in enumerate(lines):
    if "|" in line and "_Vind,_kias" in line:
        header_index = i
        break

if header_index is None:
    print("ERROR: Could not find a valid header line with column names.")
    raise SystemExit(1)

columns = parse_header_line(lines[header_index])

# Find required columns
speed_idx, speed_name = pick_column_index(columns, SPEED_CANDIDATES)
aoa_idx, aoa_name = pick_column_index(columns, AOA_CANDIDATES)
alt_idx, alt_name = pick_column_index(columns, ALT_CANDIDATES)
time_idx, time_name = pick_column_index(columns, TIME_CANDIDATES)

if speed_idx is None or aoa_idx is None or alt_idx is None:
    print("ERROR: Missing required columns.")
    print(f"Found columns: {columns}")
    raise SystemExit(1)

print("Detected columns:")
print(f"  Speed: {speed_name} at index {speed_idx}")
print(f"  AoA:   {aoa_name} at index {aoa_idx}")
print(f"  Alt:   {alt_name} at index {alt_idx}")
if time_idx is not None:
    print(f"  Time:  {time_name} at index {time_idx}")
else:
    print(f"  Time:  Using step index as proxy")
print()

data_start = header_index + 1
processed = 0
warning_active = False
last_warning_time = None

# Open output CSV
with open(OUTPUT_FILENAME, mode="w", newline="") as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow([
        "Step", "Time_sec", "Altitude_ft", "IAS_kts", "AoA_deg", 
        "LoadFactor", "Vs_actual", "Vs_warning", "Warning_Active",
        "Risk_Score", "Status"
    ])
    
    print("Starting simulation...")
    print("-"*120)
    
    for step, line in enumerate(lines[data_start:], start=0):
        line = line.strip()
        if not line:
            continue
        
        values = parse_data_line(line)
        if values is None:
            continue
        
        max_needed = max(speed_idx, aoa_idx, alt_idx, time_idx if time_idx is not None else 0)
        if len(values) <= max_needed:
            continue
        
        # Extract flight parameters
        ias_kt = values[speed_idx]
        aoa_deg = values[aoa_idx]
        alt_ft = values[alt_idx]
        
        if time_idx is None:
            t_sec = float(step) * 0.1  # Assume 10Hz if no time column
        else:
            t_sec = values[time_idx]
        
        # Simulate additional parameters (in real system, these come from sensors)
        # For this simulation, we use simplified assumptions
        current_weight = AIRCRAFT_WEIGHT_LBS  # Could vary with fuel burn
        load_factor = 1.0  # Would come from accelerometer (1.0 = level flight)
        icing_detected = False  # Would come from ice detector
        flaps_deployed = False  # Would come from flap position sensor
        
        # If we had a second AoA sensor, we'd read it here
        # For now, simulate perfect redundancy
        aoa_sensor_2 = aoa_deg + 0.1  # Slight difference (within tolerance)
        
        # Run modern stall warning system
        warning_active, last_warning_time, reason, debug_info = modern_stall_warning_system(
            ias_kt=ias_kt,
            aoa_deg=aoa_deg,
            weight_lbs=current_weight,
            load_factor=load_factor,
            altitude_ft=alt_ft,
            t_sec=t_sec,
            icing_detected=icing_detected,
            flaps_deployed=flaps_deployed,
            prev_warning_state=warning_active,
            last_warning_time=last_warning_time,
            aoa_sensor_2=aoa_sensor_2
        )
        
        # Calculate risk score
        risk_score = modern_risk_assessment(
            ias_kt=ias_kt,
            aoa_deg=aoa_deg,
            vs_actual=debug_info["vs_actual_kt"],
            aoa_warning_threshold=debug_info["aoa_warning_deg"],
            load_factor=load_factor
        )
        
        # Determine status label
        if warning_active:
            status = "STALL WARNING"
        elif risk_score > 0.6:
            status = "CAUTION"
        elif risk_score > 0.3:
            status = "MONITOR"
        else:
            status = "NORMAL"
        
        # Console output (sample every 10 steps to avoid spam)
        if step % 10 == 0 or warning_active:
            print(
                f"t={t_sec:7.2f}s | Alt={alt_ft:7.0f}ft | IAS={ias_kt:5.1f}kt | "
                f"AoA={aoa_deg:5.2f}° | Vs={debug_info['vs_actual_kt']:5.1f}kt | "
                f"Risk={risk_score:4.2f} | {status:16s} | {reason}"
            )
        
        # Write to CSV
        writer.writerow([
            step,
            t_sec,
            alt_ft,
            ias_kt,
            aoa_deg,
            load_factor,
            debug_info["vs_actual_kt"],
            debug_info["vs_warning_kt"],
            int(warning_active),
            risk_score,
            reason
        ])
        
        processed += 1
        
        if PLAYBACK_SPEED > 0:
            time.sleep(PLAYBACK_SPEED)

print("-"*120)
print()
print("Simulation complete!")
print(f"Processed data points: {processed}")
print(f"Results saved to: {OUTPUT_FILENAME}")
print()
print("Output columns:")
print("  - Vs_actual: Dynamic stall speed based on weight/load factor/altitude")
print("  - Vs_warning: Speed at which warning activates (Vs + margin)")
print("  - Warning_Active: Binary stall warning state (0=off, 1=on)")
print("  - Risk_Score: Continuous risk assessment (0.0=safe, 1.0=stall)")
print("  - Status: Flight regime description")
